/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <CapSense.h>
#include <CapSense_CSHL.h>
#include <CapSense_Pins.h>
#include <CapSense_TunerHelper.h>
#include <LCD.h>
#include <MotorPWM.h>
#include <Pin_motor_for.h>
#include <Pin_motor_for_aliases.h>
#include <Clock_pwm.h>
#include <SensorInterrupt.h>
#include <SensorTimer.h>
#include <Pin_sensor.h>
#include <Pin_sensor_aliases.h>
#include <Button_left.h>
#include <Button_left_aliases.h>
#include <LeftButtonInterrupt.h>
#include <Button_right.h>
#include <Button_right_aliases.h>
#include <RightButtonInterrupt.h>
#include <CVComp.h>
#include <TapeTimer.h>
#include <Pin_CompositeSynch.h>
#include <Pin_CompositeSynch_aliases.h>
#include <FrameInterrupt.h>
#include <LineCounter.h>
#include <TapeInterrupt.h>
#include <Clock_cam.h>
#include <Pin_servo.h>
#include <Pin_servo_aliases.h>
#include <Pin_Vref.h>
#include <Pin_Vref_aliases.h>
#include <Pin_Camera.h>
#include <Pin_Camera_aliases.h>
#include <Pin_vSynch.h>
#include <Pin_vSynch_aliases.h>
#include <ServoPWM.h>
#include <CapSense_IntClock.h>
#include <CapSense_CompCH0.h>
#include <CapSense_AMuxCH0.h>
#include <CapSense_IdacCH0.h>
#include <LCD_LCDPort.h>
#include <LCD_LCDPort_aliases.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/
